
#Parameters for the espeleo_control package

# Low level control ----------  ----------  ----------

# Radius of the wheel (meters)
R: 0.1997
# Distance between the center wheels (meters)
L: 0.4347
# If true, the middle legs of the robot will be controller to be in the uwards position.
# *If the robot has wheels in the middle this flag mst be set False
SMART_LEGS: True
# Timeout, after stopping to receive commends, for sending 0 velocity to the wheels
TIME_OUT: 0.5





# Feedback linearization ----------  ----------  ----------

# Distance the control point is moved forward from the robots center
d_feedback: -0.2


# Vector field ----------  ----------  ----------

#Flag to invert the motion of the espeleorobo (move backwards)
invert_motion_flag: False

#Name of the topic in which the pose will be obtained
pose_topic_name: tf
#Type of the topic in which the pose will be obtained (options below)
# TFMessage
# Pose
# Odometry
pose_topic_type: TFMessage

#Name of the topic in which the forward and angular velocities will be published
cmd_vel_topic_name: cmd_vel

#Flag to enable a repulsive action, to repel the robot from obstacles
flag_repulsive_action: False
#Gain of the repulsive action
K_repulsive: 0.5





# Convergence gain of the vector field
K_F: 5.0
# Reference forward speed for the espeleorobo
vr: 1.0
