# Variacao minima na posicao para que o buffer seja atualizado
delta: 0.01

# Tolerancia entre o ponto tido como objetivo e posicao de parada
tolerance: 0.2

# Distancia de retorno maxima
size: 5.0

# Topico contendo a odometria do robo
odometria: '/tf'
# odometria: '/robot_pose_ekf/odom_combined'
# odometria: '/realsense/odom/sample'

# Child frame id
<<<<<<< HEAD
# child_frame_id : 'base_link'
child_frame_id : "realsense_pose_frame"


=======
# child_frame_id: 'base_link'
child_frame_id: 'realsense_pose_frame'
# child_frame_id: 'EspeleoRobo'
>>>>>>> 44b91c7547744c957dd28e7f23ef1190fab2a338
